name: Publish

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.4
    - name: Install dependencies
      run: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
    - name: Login to git
      run: |
        git config --global user.email "enfipy@gmail.com"
        git config --global user.name "David Ackerman"
    - name: Run publish script
      run: |
        bundle install
        bundle exec rake -t
        bundle exec rake install
        bundle exec rake release
